name: Generate Staging API
on:
  push:
    branches:
      - master
jobs:
  swagger:
    name: Swagger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.RUN_SA_KEY }}
      - name: Install gcloud Beta components
        run: gcloud components install beta
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
      - name: Deploy Config to API Gateway
        run: gcloud beta api-gateway api-configs create $(node -e "console.log(require('./package.json').version.replace(/[.]/g, '-'));") --api=refundable-beta --openapi-spec=api-spec-staging.yml --project=refundable-beta-portal
      - name: Set new Config Live
        run: gcloud beta api-gateway gateways update refundable-api-gateway-x --api-config=$(node -e "console.log(require('./package.json').version.replace(/[.]/g, '-'));") --api=refundable-beta --project=refundable-beta-portal --location=europe-west1
