name: Test and Build
on:
  push:
    branches:
      - master
jobs:
  swagger:
    name: Swagger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.RUN_SA_KEY }}
      - name: Install Base Dependencies
        run: npm install
      - name: Generate YAML Files
        run: node generate-api-files.js
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui/staging
          spec-file: api-spec-staging.yml
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui/production
          spec-file: api-spec-production.yml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
      - name: Deploy to API Gateway
        run: gcloud beta api-gateway api-configs create \
          $(node -e "console.log(require('./package.json').version.replace(/[.]/g, '-'));") \
          --api=refundable-beta \
          --openapi-spec=api-spec-staging.yml \
          --project=refundable-beta-portal \
          --quiet
